# Use an official Nginx image as the base image
FROM nginx:alpine
# Set the working directory in the container
WORKDIR /usr/share/nginx/html 
# Copy the current directory contents into the container at /app
COPY . .
